# Generated by Django 5.0.7 on 2024-08-30 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_name', models.CharField(max_length=100)),
                ('Project_image', models.ImageField(blank=True, upload_to='Profile')),
                ('Description', models.CharField(max_length=500)),
                ('Start_date', models.DateField()),
                ('Deadline', models.DateField()),
                ('Technology', models.CharField(default='SOME STRING', max_length=50)),
                ('Manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['Project_name'],
            },
        ),
    ]
