# Generated by Django 5.1 on 2024-09-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='Project_image',
            field=models.ImageField(blank=True, upload_to='static/Profile'),
        ),
    ]
