# Generated by Django 5.0.7 on 2024-08-28 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='Phone_number',
            new_name='phone_number',
        ),
    ]
