# Generated by Django 5.1 on 2024-09-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_alter_employees_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Profile_image',
            field=models.ImageField(blank=True, upload_to='static/employees'),
        ),
    ]
