# Generated by Django 5.0.7 on 2024-08-30 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0002_rename_phone_number_employees_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={},
        ),
        migrations.RemoveField(
            model_name='employees',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='username',
        ),
    ]
