# Generated by Django 5.0.7 on 2024-08-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0003_alter_employees_options_remove_employees_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
