# Generated by Django 5.0.7 on 2024-08-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0007_employees_groups_employees_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Profile_image',
            field=models.ImageField(blank=True, upload_to='Profile'),
        ),
    ]
