# Generated by Django 5.0.7 on 2024-08-30 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0008_alter_employees_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Joining_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
    ]
