# Generated by Django 5.0.7 on 2024-08-31 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0009_alter_employees_joining_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employees',
            options={'ordering': ['Employee_name']},
        ),
    ]
