# Generated by Django 5.1 on 2024-09-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0010_alter_employees_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Profile_image',
            field=models.ImageField(blank=True, upload_to='static/Profile'),
        ),
    ]
