# Generated by Django 5.1 on 2024-09-03 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
