# Generated by Django 5.1 on 2024-09-05 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_management', '0001_initial'),
        ('Tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='Project_name',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='Assigned_to',
            field=models.ForeignKey(default='string', on_delete=django.db.models.deletion.CASCADE, to='Project_management.project_manager'),
        ),
    ]
