# Generated by Django 5.1 on 2024-09-02 07:58

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_name', models.CharField(max_length=100)),
                ('Start_date', models.DateField(auto_now_add=True)),
                ('Deadline', models.DateField(default=datetime.datetime.now)),
                ('Comments', models.CharField(blank=True, max_length=100)),
                ('Status', models.CharField(choices=[('1', 'Pending'), ('2', 'Working'), ('3', 'Done'), ('4', 'Overdue')], default=1, max_length=7)),
                ('Assigned_to', models.ForeignKey(default='string', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Projects.project')),
            ],
            options={
                'ordering': ['Task_name'],
            },
        ),
    ]
