# Generated by Django 5.1 on 2024-09-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Subject', models.CharField(max_length=100)),
                ('Message', models.TextField()),
            ],
            options={
                'ordering': ['Name'],
            },
        ),
    ]
